[package]
name = "iced_audio"
version = "0.13.0"
authors = [
  "Billy Messenger <https://github.com/BillyDM>",
  "Michał Kalbarczyk <https://github.com/fazibear>"
]
license = "MIT"
edition = "2021"
keywords = ["iced", "gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "An extension to the Iced GUI library with useful widgets for audio applications"
homepage = "https://github.com/iced-rs/iced_audio"
documentation = "https://docs.rs/iced_audio"
repository = "https://github.com/iced-rs/iced_audio"
readme = "README.md"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
iced = { version = "0.13.1", default-features = false, features = ["advanced"] }

[dev-dependencies]
iced = { version = "0.13.1" }

[features]
knob = ["iced/canvas"]
h_slider = ["iced/canvas", "iced/image"]
v_slider = ["iced/canvas", "iced/image"]
ramp = ["iced/canvas"]
xy_pad = ["iced/canvas"]
mod_range_input = ["iced/canvas"]

default = [
  "knob",
  "h_slider",
  "v_slider",
  "ramp",
  "xy_pad",
  "mod_range_input"
]
